pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}
plugins {
    id "org.gradle.toolchains.foojay-resolver-convention" version "1.0.0"
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        google()
        flatDir {
            dirs "$rootDir/app/libs"
        }
        maven { url = "https://jitpack.io" }
        maven { url = "https://chaquo.com/maven" }
        maven {
            url = "http://4thline.org/m2"
            allowInsecureProtocol = true
        }
    }
}
rootProject.name = "TV"
include ':app'
include ':common'
include ':catvod'
include ':chaquo'
include ':quickjs'
include ':youtube'
include ':hook'
include ':mpv'

// 定義 SmartTube 核心模組的路徑
gradle.ext.sharedModulesRoot = new File(settingsDir, 'SharedModules')
gradle.ext.sharedModulesConstants = new File(gradle.ext.sharedModulesRoot, 'constants.gradle')
if (gradle.ext.sharedModulesRoot.exists()) {
    apply from: new File(gradle.ext.sharedModulesRoot, 'core_settings.gradle')
}

gradle.ext.mediaServiceCoreRoot = new File(settingsDir, 'MediaServiceCore')
if (gradle.ext.mediaServiceCoreRoot.exists()) {
    apply from: new File(gradle.ext.mediaServiceCoreRoot, 'core_settings.gradle')
}
